import openai
#import preferences as pref

#Important : <4097> Is The Maximum Value Of <maxCharacters> Due To Free Subscription Limitation : This Includes The Question Characters

# This Key Is Unique For Every GPT Account And Is Essential For Initializing GPT
openai.api_key = "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"

# This Function Returns The Output Given By ChatGPT
def GenerateResponse(Question, maxCharacters):
    # Generate a response from ChatGPT
    response = openai.Completion.create(engine="text-davinci-002",prompt=Question,max_tokens= maxCharacters)  #Max Tokens Represent The Maximum Amount Of Characters That The Response Can Have

    # This is the text that was generated by CHATGPT
    chatGPT_result = response.choices[0].text

    print(chatGPT_result)


#GenerateResponse("Write a program to calculate prime no in c", 4000)






